name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest dvc[s3] boto3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Pull dataset from DVC remote
        run: dvc pull data/raw/credit_risk_dataset.csv

      - name: Run lint
        run: flake8 src

      - name: Run unit tests
        run: pytest tests/

      - name: Sanity model training
        run: |
          head -n 500 data/raw/credit_risk_dataset.csv > data/raw/sample.csv
          python src/data_ingest.py --sample 500 --input data/raw/sample.csv
          if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
            echo "[INFO] AWS credentials not found. Running training without S3 upload."
            python src/train_and_tune.py --sample 500 || true
          else
            python src/train_and_tune.py --sample 500
          fi

  cd:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt dvc[s3] boto3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Pull dataset from DVC remote
        run: dvc pull data/raw/credit_risk_dataset.csv

      - name: Run DVC pipeline
        run: dvc repro

      - name: Push data/model to remote
        run: dvc push

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 \
            | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and push Docker image
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/credit-risk-flask:latest
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Check model file
        run: ls -lh model.tar.gz

      - name: Upload model to S3
        run: aws s3 cp model.tar.gz s3://mlops-credit-yuhui/model/model.tar.gz

      - name: Update SageMaker endpoint
        env:
          SAGEMAKER_ROLE_ARN: ${{ secrets.SAGEMAKER_ROLE_ARN }}
        run: python scripts/update_sagemaker_endpoint.py
